import Navbar from "@/components/Navbar";
import "./globals.css";

import { Roboto } from "next/font/google";
import Header from "@/components/Home/components/Header/Header";

const roboto = Roboto({
  weight: ["100", "300", "500", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {" "}
        <Header />
        <div className="min-h-screen py-5">{children}</div>
      </body>
    </html>
  );
}
